### ISSUE TITLE
Enable rtf file conversion to pdf before printing

### ISSUE THREAD

**Issue by tina-ux** [freedomofpress/securedrop-export#108]
Journalists often receive .rtf files in their sd inbox that they would like to print in order to sanitize, share with colleagues or save to their physical archives. Those files sometimes print out as a garbage string, or as text interspersed with garbage strings.

A solution is to convert .rtf files to pdf before printing. 

**User story:** _As a journalist user, I would like to successfully print .rtf files that  are submitted to my securedrop instance._

**Comment by eaon** [comment]
Briefly talked with @zenmonkeykstop about this earlier today, and we came to the conclusion that "how we treat files in SDW" should probably be a larger conversation with a more coordinated effort, because this would also affect the client: the template the client uses does not have LibreOffice installed, but it _should_ also be aware which file types are supported for printing. Going for the 1 line hotfix for now, I will file new issues for the larger coordinated effort.
