### ISSUE TITLE
Supress missing printer driver popup

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-export#37]
## Description

We should suppress this popup if we don't want people to install the driver using this service.

![Screenshot_2019-12-04_14-20-17](https://user-images.githubusercontent.com/4522213/70188308-2edef500-16a5-11ea-82e3-12302ccd0185.png)

**Comment by emkll** [comment]
After investigation, the most straightforward way is to disable notifications at the window-manager level for sd-export-* vms. This means, however, that the existing export notifications will no longer work.

I have proposed a PR to the packaging repo to disable these notifications (https://github.com/freedomofpress/securedrop-debian-packaging/pull/122).

While not strictly necessary, I have opened a PR to this repo to remove the notification code, since it will no longer work under a system configured with the above.
