### ISSUE TITLE
device mapper sometimes busy when exporting

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-export#58]
# Description

We've removed the "Export Successful" message from `securedrop-export` and are [getting ready](https://github.com/freedomofpress/securedrop-client/pull/666) for the client to wait until either no status (meaning success) or a status containing an error message is returned. https://github.com/freedomofpress/securedrop-client/pull/666 surfaces a bug where sometimes the client receives an error message `device-mapper: remove ioctl on luks-<unique id> failed: Device of resource busy`, however the file transfer is successful. 

# More details

The bullets below indicate that the device is properly being mounted/unmounted locked/unlocked:

* Looking at `securedrop-export` logs, I see all three of these logs appear when this error is returned to the client: https://github.com/freedomofpress/securedrop-export/blob/9526fe4558a4fa2872cd4b9249ce9865030eeb99/securedrop_export/disk/actions.py#L180-L192

* I also see the 2 "Device removed" Qubes popups when we mount the device after unlocking it and the 2 "Device available" popups when we unmount and lock the device

* Exporting a file again from the client, after seeing this error, will sometimes succeed without returning the error message `device-mapper: remove ioctl on luks-<unique id> failed: Device of resource busy`

* Regardless of the error, the file seems to successfully transfer each time

**Comment by creviera** [comment]
Since this is not reproducible we should remove the `release blocker` tag or just close this issue.

**Comment by redshiftzero** [comment]
Since we still haven't seen this in QA, I'm going to close this for now, let's reopen if we see again

**Comment by rocodes** [comment]
Great(?) news, I have just repro'd this when I was testing scenarios for #40. 

Error msg 1 (can repro almost 100% of the time):
![sd_export_already_unlocked_error](https://user-images.githubusercontent.com/22777700/151177269-cb31f861-7a81-482e-b467-d2bc65bb567d.png)

STR: insert USB, unlock via Nautilus in sd-devices (I have repro'd with both the "Forget password immediately" option and the "remember for x time" options), navigate to a folder inside the export device (eg a previous export archive) to keep the device busy

![sd_devices_unlock_options](https://user-images.githubusercontent.com/22777700/151177270-5ccc5981-b910-4707-b9c8-993fffdca1ec.png)

Error msg 2 (can repro 100% of the time)  if you keep the device busy by e.g. `cd` ing into the `/media/user/device-id-xxxxx` directory in an `sd-devices` terminal 
![sd_devices_unmount_target_busy](https://user-images.githubusercontent.com/22777700/151182309-1b533013-6cc1-4a56-93f2-4015eb34491a.png)

- The export occurs successfully, but an error message is shown (see attached screenshot)
- [Logs](https://github.com/freedomofpress/securedrop-export/files/7942259/busy.txt)
- The reason the error shows up here is because the cleanup part of our 'copy submission` method also locks and unmounts the drive, so the user sees an error (with unmounting the drive) even though the export itself succeeded.

**Comment by rocodes** [comment]
I think a user would have to go out of their way to encounter this issue (i.e. by interacting directly with `sd-devices` to unlock the device instead of using the export workflow), and I think the fixes are pretty straightforward (such as clearer messaging in the export flow that indicates that the export itself was successful, but there's a problem unmounting the drive, and/or better error-handling as we unmount the drive if we detect that it's in use by another process on sd-devices).

**Comment by gonzalo-bulnes** [comment]
I see you've commented on this issue before @rocodes. It seems to me that this scenario would be handled as [`Status.ERROR_EXPORT_CLEANUP`](https://github.com/freedomofpress/securedrop-export/pull/105/files#diff-dcfd23a386fcec623e1f72b7b69ed2c760d6996f945eb95bd1300989bba4942bR18), wouldn't it?
