### ISSUE TITLE
Build fails because some APT packages cannot be retrieved

### ISSUE THREAD

**Issue by gonzalo-bulnes** [freedomofpress/securedrop-export#92]
The `main` CI build has been broken for a few days, because some APT packages cannot be retrieved.
Error: https://app.circleci.com/pipelines/github/freedomofpress/securedrop-export/269/workflows/da4777bc-2e01-4d56-803f-d56867656bea/jobs/747?invite=true#step-102-100

Lead: note that **test-buster** is not failing in the latest of @rocodes branches! :point_right: https://app.circleci.com/pipelines/github/freedomofpress/securedrop-export/268/workflows/eaa3f8f5-36ab-40cf-b6f0-3e50a8860476

**Comment by eloquence** [comment]
Can this be closed or is further follow-up required here?

**Comment by legoktm** [comment]
This was fixed in #90. The problem was that we were not running `apt update` before trying to install the package. One of the dependencies we were trying to install had moved to a new version since the apt index cache already in the container had been updated.

Because the plain `debian:{codename}` images don't have any apt index cache in them, we always have to run `apt update` at the start of a build before packages can be installed, so it's unlikely we'll repeat this issue in the future.
